version: '3.8'

services:

  ordinario_abs:

    image: mysql:latest

    environment: 

      MYSQL_ROOT_PASSWORD: 12345

      MYSQL_DATABASE: ordinario_modelo_admin

      MYSQL_USER: myuser

      MYSQL_PASSWORD: 12345

    ports:

      - "33060:3306"

    volumes:

      - ./mysql_data:/var/lib/mysql
